FROM python_boto3

RUN apt-get update \
     && apt-get -y install python3-pip \
     && pip install boto3 \
     && apt-get install git -y \
     && apt-get install -y iputils-ping
WORKDIR /eks-cluster-terraform

RUN git clone https://github.com/KinzP/eks-cluster-terraform.git /eks-cluster-terraform

ENTRYPOINT ["tail", "-f", "/dev/null"]
