#App Deployment 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-vol
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-vol
        configMap:
          name: index-html-configmap1
---
#ConfigMap1
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap1
data:
  index.html: |
    <html><body><h1>This is Deployment One</h1></body></html
