FROM ubuntu:22.04

RUN apt-get update \
     && apt-get -y install python3-pip \
     && pip install boto3 \
     && apt-get install git -y \
     && apt-get install -y iputils-ping

WORKDIR /cicd_terraform

RUN git clone https://github.com/KinzP/cicd_terraform.git /cicd_terraform

ENTRYPOINT ["tail", "-f", "/dev/null"]



