FROM ubuntu:22.04

RUN apt-get update \
     && apt-get -y install python3-pip \
     && pip install boto3 \
     && apt-get install git -y \
     && apt-get install -y iputils-ping
 
 WORKDIR /python_LUIT
  
RUN git clone https://github.com/ifeanyiro9/python_LUIT.git /python_LUIT
  
ENTRYPOINT ["tail", "-f", "/dev/null"]
